version: '3.4'

services:
  springboot-service:
    image: hrms-backend-fixed
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/hrms2
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql-service
    networks:
      - mynetwork

  frontend:
    image: hrms-frontend-fixed
    ports:
      - "4200:80"
    depends_on:
      - mysql-service
    networks:
      - mynetwork

  mysql-service:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hrms2"
      MYSQL_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql-data:
