apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-simple
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-simple
  template:
    metadata:
      labels:
        app: backend-simple
    spec:
      containers:
        - name: backend
          image: dadarao/hrms-backend-fixed
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/hrms2
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          # Use TCP socket check instead of HTTP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
