apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-fixed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-fixed
  template:
    metadata:
      labels:
        app: frontend-fixed
    spec:
      containers:
        - name: frontend
          image: dadarao/hrms-frontend-fixed
          ports:
            - containerPort: 80
          # Add environment variable to configure backend service URL
          env:
            - name: BACKEND_URL
              value: "http://backend-service:8080"
